Vagrant.configure(2) do |config|
  config.vm.box = 'CentOS-6.6-64-V1'
  config.vm.box_url = '\\\\172.16.0.9\\Magento\\Vagrant\\Boxes\\CentOS-6.6-64-V1.box'
  config.vm.synced_folder '../../../', '/vagrant'
  config.vm.network 'private_network', ip: '192.168.56.110', netmask: '255.255.0.0'
  
  config.vm.provider 'virtualbox' do |v|
	v.name = 'magento-dev'	
  end
  
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = 'puppet/manifests'
    puppet.module_path = 'puppet/modules'
    puppet.manifest_file = 'init.pp'
  end
end